apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: jammy-minimal
  labels:
    harvesterhci.io/imageDisplayName: jammy-minimal
    harvesterhci.io/os-type: ubuntu
  namespace: default
spec:
  displayName: jammy-minimal
  sourceType: download
  url: https://cloud-images.ubuntu.com/minimal/releases/jammy/release/ubuntu-22.04-minimal-cloudimg-amd64.img
